apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transit
resources:
  - namespace.yaml
  - poller.yaml
  - kafka.yaml
  - resolver-keda.yaml
  - api.yaml
  - batch-cronjob.yaml
